package justin.http_client

import scala.Predef._

/** This object was generated by sbt-buildinfo. */
case object BuildInfo {
  /** The value is "justin-db-client-http". */
  val name: String = "justin-db-client-http"
  /** The value is "0.1-511-gf6e41b7-SNAPSHOT". */
  val version: String = "0.1-511-gf6e41b7-SNAPSHOT"
  /** The value is "2.12.1". */
  val scalaVersion: String = "2.12.1"
  /** The value is "0.13.13". */
  val sbtVersion: String = "0.13.13"
  /** The value is scala.Some("f6e41b74c3b2b88d879dd7c860d1c660769aae08"). */
  val gitHeadCommit: scala.Option[String] = scala.Some("f6e41b74c3b2b88d879dd7c860d1c660769aae08")
  /** The value is "master". */
  val gitCurrentBranch: String = "master"
  override val toString: String = {
    "name: %s, version: %s, scalaVersion: %s, sbtVersion: %s, gitHeadCommit: %s, gitCurrentBranch: %s" format (
      name, version, scalaVersion, sbtVersion, gitHeadCommit, gitCurrentBranch
    )
  }
  val toMap: Map[String, Any] = Map[String, Any](
    "name" -> name,
    "version" -> version,
    "scalaVersion" -> scalaVersion,
    "sbtVersion" -> sbtVersion,
    "gitHeadCommit" -> gitHeadCommit,
    "gitCurrentBranch" -> gitCurrentBranch)

  val toJson: String = toMap.map(i => "\"" + i._1 + "\":\"" + i._2 + "\"").mkString("{", ", ", "}")
}
